server:
  port: 8000
spring:
 application:
  name: apigateway-service
 cloud:
  gateway:
   routes:
    - id: memberservice
      uri: http://localhost:8081/
      predicates:
        - Path=/api/member/**
    - id: orderservice
      uri: http://localhost:8082/
      predicates:
        - Path=/api/order/**
    - id: productservice
      uri: http://localhost:8083/
      predicates:
        - Path=/api/product/**
    - id: userservice
      uri: http://localhost:8084/
      predicates:
        - Path=/api/user/**
    - id: deliveryservice
      uri: http://localhost:8085/
      predicates:
        - Path=/api/orderdelivery/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
