spring:
 application:
  name: apigateway-service
 cloud:
  gateway:
   routes:
    - id: memberservice
      uri: http://localhost:8081/
      predicates:
        - Path=/api/member/**
    - id: orderservice
      uri: http://localhost:8082/
      predicates:
        - Path=/api/order/**
    - id: userservice
      uri: http://localhost:8084/
      predicates:
        - Path=/api/user/**
